language: node_js

node_js: '8'

services:
  - mongodb

jobs:
  include:
    - stage: test
      script:
        - npm run test
    - stage: deploy
      name: Deploy on Heroku
      script: skip
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_faebc38c4945_key -iv $encrypted_faebc38c4945_iv -in .env.enc -out .env -d
        - npm run build
      deploy:
        provider: heroku
        api_key:
          secure: DR6sukqK9ikDr8xXUh8WIZIlSg0EBxX7L2xZREKGhPBa/bHH7nDc/AkB6h/Qb59aXc+l7ZLvuXkay9NaMBcAzAzJh/SBFe3TeVvkbH34bNqCetsTvPzkvL+zOwGD2yW1jX16jZ5EyM9FGI9DGtwgVjseHmZRFJ2/mT11chNQCLo13uz+1ro1vqH0WcCWM7NpXuAYYQxiNijYukoofip2DVVpa5rSAHKc317Y7Bk/NeNS9YE23uHNKI6OL8hHDC/dNWb1F93rsxnZSAp42cVyF33vebhSSp3rF6Zwb9UlAil+QfhcKgLgdwrSq9q4i3yLA/98TFpYier8LKIki0C1IUcSu9C5q4HFitu+jE6av+xQyS3blsQCrY6lACD/uAxJFTfmjXNj7sb+XaomGwhOAscNqxyWx5gO/BSDO2XrVcQjAyNH9VE0FEyucuK/v/aPEeUz6SQn/eycW9SERUFq0GJNbQ/f55c+hBBvzeCVvvNxF1Q8+/mx1chp9BNZml8S0oj7YvIRoUOjGJJC0MpBYyYk8NuOs57/ayxOt3hENXWJMQVKYdCq8W42iL92k+Ju3a9gFyJZu+cplECEzrl8hqnsIZHascg/yHeEdJnINadUdlFQkBRBrEGlAbrNgGpx6i5cqrzegkAYFWw55Ed9ADLj/BAShLGGQubrCe9MqGE=
        app: gaslow
        on:
          repo: matitalatina/gaslow
          branch: master
        env:
          - NODE_ENV=production
        skip_cleanup: true
    - name: Deploy on AWS (Serverless)
      before_install:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
      script: skip
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_faebc38c4945_key -iv $encrypted_faebc38c4945_iv -in .env.enc -out .env -d
      deploy:
        provider: script
        on:
          repo: matitalatina/gaslow
          branch: master
        script: npm run build-package-deploy
      skip_cleanup: true

cache:
  directories:
    - node_modules
